version: '3.8'
services:
  atm:
    build: .
    image: atm-ui:latest
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - PORT=8082
      - DB_PATH=/data/db.sqlite
    volumes:
      - db-data:/data
    restart: unless-stopped
volumes:
  db-data:
